api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make   : ~
env_prep   : get-composer
env_post   :
php_conf   : timezone
php_exts   : ~
app_prep   : dep-composer
app_post   : ~
app_path   : ~
pkg_name   : augustus-library
pkg_desc   : "composer meta-package to require all augustus-* packages"
pkg_bndl   : false
